### ISSUE TITLE
Twitter Alerts Bug

### ISSUE THREAD

**Issue by CornFlakesPC** [PhantomBot/PhantomBot#2386]
PhantomBot Version: **3.3.2**
O/S Version: **Ubuntu 18.04**
Java Version: **1.8.0_265**

Detailed Description:

If set an @TWITTERUSER in the Twitter Alerts online Tweet message or in the timed online tweet message the "@" will be missing in the tweet. 

Screenshots (if applicable):

https://i.botflakes.de/DHBnKn.png
https://i.botflakes.de/c7SpH8.png
https://i.botflakes.de/8WTLbi.png
https://i.botflakes.de/A8rD4r.png

**Comment by gmt2001** [comment]
Due to the rules around mentions from a bot, we intentionally block this to prevent misuse

You can read the rules [here](https://help.twitter.com/en/rules-and-policies/twitter-automation) in Section II.B.2

The rules are, basically:
1. The user must very clearly and explicitly opt-in to it via Tweet or Twitter DM, and indicate that your bot specifically is authorized to do so, or you must make it very clear in a Tweet or your profile that a mention, reply, like, or retweet will trigger it (if using automated triggers). Note that follows are not valid for this purpose
2. You must tell the user how to opt-out, and it must be very easy and straightforward to do so. You must honor the opt-out in a reasonably fast time. If using automated triggers based on Tweets or DM's, this could be as simple as not triggering it
3. Only 1 mention is allowed per bot post
4. If the bot is triggered by a reply, it must use a reply (no standalone tweets triggered by a reply)

If you think you can follow the rules and want to go ahead with this anyway, you would have to make a custom build of the bot

The relevant lines to modify are
https://github.com/PhantomBot/PhantomBot/blob/9d2955ab166e16387fe1bd59da0755ae9bd1ee26/source/com/illusionaryone/TwitterAPI.java#L173

and 

https://github.com/PhantomBot/PhantomBot/blob/9d2955ab166e16387fe1bd59da0755ae9bd1ee26/source/com/illusionaryone/TwitterAPI.java#L195

**WARNING:** By making this modification you relieve PhantomBot and all of it's developers, contributors, users, etc from all liability for any consequences that may result from failure to abide by, and keep up-to-date with, Twitter's policies. You acknowledge that, should Twitter determine that you are not abiding by their policies, you may be banned, including permanently, from Twitter. You also acknowledge and accept that Twitter has the right to change these policies at any time without notification. No support is provided by PhantomBot once this modification is made

**Comment by CornFlakesPC** [comment]
Ah didn't thought about that. Thanks for your answer! Have great weekend
