### ISSUE TITLE
Twitter not pulling Tweets?

### ISSUE THREAD

**Issue by MrCallumX** [PhantomBot/PhantomBot#2421]
PhantomBot Version: 3.3.5
O/S Version: 
Java Version: 
Web Browser Version (if Panel related):

Detailed Description: The console on startup is stating that the Twitter API is successfully connected. However no matter what we have tried in the panel, we cannot get it to pull tweets from twitter. 

I have ensured that the keys and secrets are all correct. It is running on a server using SSL, however also did not work running on a local machine without SSL. 

Steps to Reproduce:

Logs:

Screenshots (if applicable):

**Comment by arricc** [comment]
I have the same issue. My bot has stopped pulling anything from Twitter. I've reset all of the Twitter keys, the logging shows "Authenticated with Twitter API" but nothing :(

**Comment by MrCallumX** [comment]
@arricc Was there a specific update or something that broke it? How long ago did it stop working? 

Am trying to figure out if it is something broken already in this build or if it is a setting we have not set up correctly. 

Thanks 👍

**Comment by arricc** [comment]
@CallumXGames not sure to be honest - I tend to update to the latest version within a week of release. It's been broken for at least a couple of weeks and I only found time to investigate it yesterday,

**Comment by wheezer1987** [comment]
Any update on this issue? I'm having the same problem

**Comment by IsegrimDE** [comment]
Seems like nobody is assigned to this as of yet.
This features was really usefull to me since my viewers could just click to retweet or like.

**Comment by C74K** [comment]
not working.

**Comment by Sartharon** [comment]
Skimming through the `TwitterCache ` code i feel this line could be a problem if users dont wanna have the bot post Twitterposts in the twitch chat ( meaning those options are all false) but want to have the bot post only on discord. Hence the cache wont be updated which leads to the event not firing and nothing will be posted on discord. @gmt2001 will probably correct me if i'm wrong

UpdateCache will leave here since the needed settings/DB entries are handled by the the twitch alerts section:
[TwitterCache.java#L156](https://github.com/PhantomBot/PhantomBot/blob/22eeede216fb7ad7b7006e7de0b7f1fbb6950835/source/tv/phantombot/cache/TwitterCache.java#L156)
       ` if (!reward_retweets && !poll_retweets && !poll_mentions && !poll_hometimeline && !poll_usertimeline) {
            return;
       }`
       
Some refractor would be nessecary or adding poll settings for the discord side

**Comment by gmt2001** [comment]
Twitter4j is abandoned

Replace with https://github.com/redouane59/twittered
