### ISSUE TITLE
PB only posts once on Twitter

### ISSUE THREAD

**Issue by Alucard2112** [PhantomBot/PhantomBot#2571]
PhantomBot Version: 3.5.0-NB-10092021 (nightly_build) (Revision: 1045ed8)
Operating System: Linux
Java Version: 11.0.4+10-LTS
Web Browser Version (if Panel related):

Detailed Description:
If I go live at least twice a day, the bot will only post an online notification once on Twitter. I do not actually know how long the intervall between streams has to be for the bot to post again. Today, it was about 6h difference and the bot did not post the second stream.

Steps to Reproduce:
Go online twice on the same day.

Logs:
No logs for errors were created.

Screenshots (if applicable):

**Comment by gmt2001** [comment]
There is an intentional 8 hour cooldown to prevent it from spamming during a typical length stream from streamers who do long daily streams, just in case of API issues. You could edit this yourself in your copy of the script if you want, but you will have to redo the edit every time you update the bot.

The relevant file is `scripts/handlers/twitterHandler.js` right near the top.

https://github.com/PhantomBot/PhantomBot/blob/1045ed81843e88d4d6fe074790c6f151b36d68f7/javascript-source/handlers/twitterHandler.js#L33

Just change the `480` to the number of minutes you want the cooldown to be.

**Comment by Alucard2112** [comment]
Tha ks for the reply :)
Wouldn't it be better that, instead of hardcoding, one would be able to set the CD via an option within the twitter alert?
Also, what is the difference between the Discord implementation and Twitter? Discord does not seem to need a CD in order to function^^

**Comment by gmt2001** [comment]
The Discord script is just for posting inbound tweets to a Discord channel. The Twitch script will actually tweet when going live

**Comment by Alucard2112** [comment]
Thanks for the clarification :)
